### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ahmedshovon** [jbferet/biodivMapR#1]
Error: Failed to install 'biodivMapR' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘matrixStats’

**Comment by jbferet** [comment]
this looks like a R issue due to matrixStats being currently used in another R session on your computer, or unexpected location of your package install. 
please check the solution suggested for similar problem here:
https://stackoverflow.com/questions/26570912/error-in-installation-a-r-package

once you fix it, installation of biodivMapR should run with no issue.
