### ISSUE TITLE
Error during executing perform_PCA

### ISSUE THREAD

**Issue by wuqinyu291** [jbferet/biodivMapR#13]
Dr. Féret,
Thanks for your package. It's very exciting. There's one problem that's been bugging me for a long time. When I ran your example_script, It work well. But when I tried to import a my own raster and ran the demo code on it I got the following error:
PCA_Output <- perform_PCA(Input_Image_File = Input_Image_File, Input_Mask_File = Input_Mask_File,
+                           Output_Dir = Output_Dir, TypePCA = TypePCA, FilterPCA=FilterPCA,
+                           nbCPU = nbCPU, MaxRAM = MaxRAM, Continuum_Removal = Continuum_Removal)
Exclude spectral domains corresponding to water vapor absorption
The following spectral domains (min and max spectral band in nanometers) will be discarded
            [,1] [,2]
Excluded_WL    0  400
             895 1005
            1320 1480
            1780 2040
Please define the input variable Excluded_WL when calling perform_PCA
if you want to modify these spectral domains
[1] "Extract pixels from the images to perform PCA on a subset"
Error in CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  : 
  negative length vectors are not allowed
In addition: Warning messages:
1: In as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names,  :
  Item 1 has 0 rows but longest item has 2; filled with NA
2: In as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names,  :
  Item 2 has 0 rows but longest item has 2; filled with NA
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
5: In max(rc$col) : no non-missing arguments to max; returning -Inf
6: In min(rc$rowInBlock) : no non-missing arguments to min; returning Inf
7: In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
  NAs introduced by coercion to integer range
8: In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
  NAs introduced by coercion to integer range
9: In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
  NAs introduced by coercion to integer range

I don't know what is going on, can you give me some advice?
Thank you very much!

**Comment by jbferet** [comment]
@wuqinyu291 thank you for your feedback on the use of biodivMapR. 
This error is usually resulting from an 'excessive' filtering of the data. Here, your mask may include little to no valid pixels, maybe because of the radiometric filtering (if you used it before computing PCA). 

I suggest that you open the raster file named 'ShadeMask_Update' (in your result directory), and check if it actually contains valid pixels (0 values are masked, 1 values are valid pixels kept for the analysis). 
If ShadeMask_Update has 0 values only (or very low amount of 1 values), then you may want to adjust the thresholds for the radiometric filtering, in order to make sure you keep more valid pixels. 

If ShadeMask_Update appears as valid, then I will need more information to understand this: in this case, can you prepare an image subset which allows you to reproduce the error, and share with me the image subset and corresponding R scripts?

Thank you
