### ISSUE TITLE
Processing data with higher resolution

### ISSUE THREAD

**Issue by Vro1234** [jbferet/biodivMapR#16]
Hi, 
I'd like to process a PlanetScope image (resolution of 3x3m). However, I cannot calculate alpha and beta diversity. 
For alpha, it starts mapping but after a while the 
Error cannot allocate vector of size 10.9 Gb occurs. 

Is there a way to process PlanetScope data other than processing little parts of it? 

Thank you!

**Comment by jbferet** [comment]
Hi @Vro1234, 
biodivMapR is supposed to handle very large datasets, including mosaics of Sentinel-2 tiles and airborne imaging spectroscopy. Then you should be able to process Planet data

Here are a few suggestions which may help :
- First, make sure that you are using the latest version (currently v1.10.1), as I rewrote multiple functions very recently to better deal with large images and manage RAM when distributing the computation on multiple cores. 
- also make sure that the input parameters of the different functions are still correct if you are using scripts from a previous biodivMapR version on this latest version. A few parameters changed, as I tried to make it more simple. I will check if the tutorial is correctly updated. 
- the MaxRAM parameter does not actually correspond to the maximum RAM allowed to allocate. This is the maximum chunk size read by a core/CPU at once (I should rename it because this is counter intuitive). Then it inflates with successive computations. Therefore, I recommend starting with default value (MaxRAM = 0.25) to make sure the processing will not require unreasonable amount of RAM. 
- if the problem still occurs, then you may want to set MaxRAM = 0.1. But this is surprising...

Can you please provide more information on your case?
- how many spectral bands are you processing, and what are your image dimensions?
- did you provide a proper header file (.hdr) including your image metadata?
- what is the configuration of your computer?

If you still have this problem, I would need a screenshot of all the messages printed by biodivMapR during the process, as well as your R script. Then I can check if something is obviously wrong in the parameterization. Let me know if you can provide this via email. if you still have this problem, a full dataset including script and an image subset allowing reproducing the bug may be needed.

Cheers, 
jb

**Comment by Vro1234** [comment]
Thanks a lot, setting MaxRAM to 0.25 instead of 0.5 solved the issue.
