### ISSUE TITLE
Processing time for large Sentinel-2 images 

### ISSUE THREAD

**Issue by nklaudy** [jbferet/biodivMapR#20]
Hello, 

I am working with tile-sized Sentinel-2 images that are around 1.7Gb in size (GeoTIFF format). I proceeded according to the tutorial and got to the PCA and dimensionality reduction section, then ran the perform_PCA function. This has now been running for the last 6 hours and is still on the part [1] "Extract pixels from the images to perform PCA on a subset". As I have only little experience with large remote sensed images, I was wondering if this is an acceptable amount of time or if I may have done something wrong?

I hope that this is the right place to ask this!
 
Thanks in advance,
Nikolas

**Comment by jbferet** [comment]
Dear Nikolas, 
it seems that you may have a problem with the processing, as this step should not take hours. 
you should have a header file associated with your image, in order to provide information on the spectral bands. It seems that the incomplete description of image metadata associated with tiff files is often the cause of difficulties to process images with biodivMapR. 
I would suggest that you convert your TIFF image using the ENVI driver with gdal (using R packages such as raster, terra or stars), and that you make sure that the header file produced with this ENVI conversion includes the 'wavelength' attribute as in the following template: 
https://github.com/jbferet/biodivMapR/blob/master/inst/extdata/HDR/SENTINEL_2.hdr

It is possible to use your tiff image directly if you produce a proper header file, but you need to make sure it is correctly documented. I will try to fix the issue related to tiff images in a next version. 

best regards, 
Jean-Baptiste

**Comment by nklaudy** [comment]
Dear Jean-Baptiste, 

Thank you for the answer, I decided to download the data again, now in ENVI format and everything ran smoothly. 

Thanks for the help and kind regards, 
Nikolas
