### ISSUE TITLE
Diversity maps output resolution

### ISSUE THREAD

**Issue by JjPerezR** [jbferet/biodivMapR#29]
Hi dear developers

Is it possible to modify the output resolution of the resulting alpha and beta diversity maps made from a Sentinel 2A image? Even when I have modified the "window_size" parameter, the output pixel size is 100m. This is the default output resolution?

Regards!

JP.

**Comment by jbferet** [comment]
Dear @JjPerezR , 
If you run beta diversity mapping without prior update of window_size in alpha diversity mapping, then you may not get an update in output resolution: a file names 'SpectralSpecies_Distribution' is produced when running map_alpha_div, and this is the file constraining the output distribution for both alpha and beta diversity. This was not very judicious from me to code it this way.
Can you confirm that the problem you met occured when trying to produce various output resolution of beta diversity, with no update on alpha diversity?

This should be fixed in a next major update of the package. 

Thank you for reporting this. If the problem is different from the one I suggest, can you send me a script allowing me to reproduce the problem with the illustration example used in the documentation? thank you!

jb

**Comment by JjPerezR** [comment]
I have resolved the confusion in accordance with the clarification provided. I was wondering why changing the 'window_size' values directly for Beta diversity map did not take effect. Now it is clear to me.

Thank you!
