### ISSUE TITLE
Error computing map_alpha_div

### ISSUE THREAD

**Issue by valeolmo** [jbferet/biodivMapR#32]
Hello,
I'm running map_alpha_div function on a Sentinel-2 image but unfortunately I'm getting this error: 
"Error in compute_SSD(Image_Chunk = SS_Chunk, window_size = window_size,  : can not find 'i' object"
I've no problems with previous steps. Can you please help me with this issue?

Thank you very much for your help,
Valentina

**Comment by jbferet** [comment]
Hi Valentina, 
thank you for your email. 
This error may occur if your image does not contain enough valid pixels. Did you check the mask provided as input, to make sure it is in agreement with what you expected to mask?
I would need you to send me the code you have been using and sufficient information to reproduce the bug, if the erro rdoes not come from the mask which is too restrictive. If possible, prepare an image subset and a code that I can run directly with no modification on my computer to reproduce the error, and share it with me via a file sharing system (my email will reject large attached files). 
thank you!
jb

**Comment by valeolmo** [comment]
Thank you for your immediate reply. It seems there's nothing wrong with the mask. I sent you a link to download code and image via email.
Thank you again.

Valentina

**Comment by jbferet** [comment]
Hi Valentina, 
thank you for sharing your script and image subset, and thank you for reporting this bug. 
Indeed, the bug was occuring when setting nbCPU to the default value (nbCPU = 1) when running the function 'map_alpha_div'. I usually use multithread so I did not identify this bug so far. 

I will push an updated version (1.14.3) which should fix the bug (by this afternoon). Meanwhile, if you want to produce your diversity maps with th ecurrent version, you can set nbCPU to a value > 1 , up to any value which does not exceed the capacity of your computer. 

Thank you for reporting this bug. Let me know if everything works past this step.
Best regards, 
Jean-Baptiste

**Comment by valeolmo** [comment]
Dear Jean-Baptiste,
With nbCPU>1 everything is working fine. Thank you very much for your help.
Best,
Valentina

**Comment by jbferet** [comment]
ok great!
version 1.14.3 is ready for install now. I am closing the issue. 
Cheers, 
jb
